import type { Metadata } from 'next'

import { Toaster } from '@/components/ui/sonner'

import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`} data-theme="light">
        {children} <Toaster richColors theme="light" />
      </body>
    </html>
  )
}
